import { Case, Evidence, TimelineEvent } from '../types';

export const INITIAL_CASES: Case[] = [
  {
    id: 'CR-2026-00124',
    subject: 'พนักงานขับรถให้บริการไม่สุภาพและขับขี่หวาดเสียว สาย 514',
    category: 'driver_conduct',
    channel: 'hotline',
    priority: 'high',
    status: 'investigating',
    complainantName: 'Sompong Jai-dee',
    complainantContact: '081-456-7890',
    complainantEmail: 's.jaidee@example.com',
    isAnonymous: false,
    busRoute: '514 (Minburi - Silom)',
    vehicleId: '12-3456 / Bus-8A',
    incidentTime: '2026-10-10T17:45:00',
    incidentLocation: 'Ratchada Intersection, near Big C',
    narrative: 'The driver was operating the vehicle extremely recklessly. They ran a solid red light at the Ratchada intersection and abruptly swerved into the left lane without signaling, nearly causing a collision with a motorcycle. Several passengers, including an elderly woman, lost their footing and fell due to harsh braking. Driver ignored passengers asking him to slow down.',
    tags: ['#RecklessDriving', '#TrafficViolation', '#PassengerSafety', '#Route514'],
    assignedInvestigator: 'Kittipong N.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 4',
    slaDeadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-10-12T09:00:00',
    updatedAt: '2026-10-14T14:30:00',
    approvalStatus: 'pending',
    managerNotes: 'Pending driver interview discovery results before taking disciplinary action.'
  },
  {
    id: 'CR-2026-00123',
    subject: 'รถโดยสารขาดระยะช่วงเวลาเร่งด่วน สาย 511',
    category: 'schedule_delay',
    channel: 'website',
    priority: 'medium',
    status: 'investigating',
    complainantName: 'Malee K.',
    complainantContact: '089-112-2334',
    complainantEmail: 'malee.k@example.com',
    isAnonymous: false,
    busRoute: '511 (Paknam - Southern Bus Terminal)',
    vehicleId: '11-8765 / Bus-3C',
    incidentTime: '2026-10-14T07:30:00',
    incidentLocation: 'Sukhumvit Soi 71 Bus Stop',
    narrative: 'Waited for bus 511 for over 50 minutes during the morning rush hour. Two buses passed by fully packed and refused to stop. Passengers accumulated over 40 people at the stop causing severe commute delays.',
    tags: ['#ScheduleDelay', '#RushHour', '#Route511'],
    assignedInvestigator: 'Wichai S.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 3',
    slaDeadline: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-10-14T08:45:00',
    updatedAt: '2026-10-14T10:00:00',
    approvalStatus: 'pending',
    managerNotes: ''
  },
  {
    id: 'CR-2026-00122',
    subject: 'เสนอแนะการเพิ่มจุดจอดรถป้ายใหม่ สาย 72',
    category: 'route_change',
    channel: 'website',
    priority: 'low',
    status: 'completed',
    complainantName: 'Anonymous',
    complainantContact: '',
    complainantEmail: '',
    isAnonymous: true,
    busRoute: '72 (Klong Toey - Thewet)',
    vehicleId: 'General Route',
    incidentTime: '2026-10-08T12:00:00',
    incidentLocation: 'Near new community mall at Rama 4',
    narrative: 'Suggesting to add an official bus stop in front of the newly opened shopping and health center on Rama 4 road to serve elderly visitors and patients.',
    tags: ['#RouteImprovement', '#PublicSuggestion', '#Route72'],
    assignedInvestigator: 'Kittipong N.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 4',
    slaDeadline: '2026-10-15T18:00:00',
    createdAt: '2026-10-08T14:00:00',
    updatedAt: '2026-10-13T16:00:00',
    approvalStatus: 'approved',
    managerNotes: 'Surveyed the area with traffic police division. Stop approved and scheduled for physical installation next month.'
  },
  {
    id: 'CR-2026-04192',
    subject: 'Bus Route 72 Delayed Schedule - Overdue Resolution',
    category: 'schedule_delay',
    channel: 'hotline',
    priority: 'high',
    status: 'overdue',
    complainantName: 'Sompong J.',
    complainantContact: '081-333-9988',
    complainantEmail: 'sompong.j@example.com',
    isAnonymous: false,
    busRoute: '72 (Klong Toey - Thewet)',
    vehicleId: '13-9090',
    incidentTime: '2026-10-01T08:00:00',
    incidentLocation: 'Thewet Terminal',
    narrative: 'Severe interval gap exceeding 75 minutes on route 72. Dispatchers failed to send replacement fleet during vehicle maintenance schedule.',
    tags: ['#Overdue', '#ScheduleDelay', '#TerminalDispatch'],
    assignedInvestigator: 'Anan P.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 4',
    slaDeadline: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-10-01T09:15:00',
    updatedAt: '2026-10-05T11:00:00',
    approvalStatus: 'revised',
    managerNotes: 'Investigation overdue: Zone manager requires immediate fleet rebalancing plan.'
  },
  {
    id: 'CR-2026-04191',
    subject: 'Driver Conduct Report - Line 511 (Aggressive Lane Changes)',
    category: 'driver_conduct',
    channel: 'social_media',
    priority: 'medium',
    status: 'investigating',
    complainantName: 'Malee K.',
    complainantContact: '085-444-1122',
    complainantEmail: 'malee.k@example.com',
    isAnonymous: false,
    busRoute: '511 (Paknam - Southern Terminal)',
    vehicleId: '11-4521',
    incidentTime: '2026-10-11T14:30:00',
    incidentLocation: 'Phetchaburi Road',
    narrative: 'Driver was speeding and continuously honking at private vehicles, refusing to stop at marked bus stations when passengers were signaling.',
    tags: ['#DriverConduct', '#Speeding', '#Line511'],
    assignedInvestigator: 'Kittipong N.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 3',
    slaDeadline: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-10-11T16:00:00',
    updatedAt: '2026-10-12T10:00:00',
    approvalStatus: 'pending',
    managerNotes: ''
  },
  {
    id: 'CR-2026-04190',
    subject: 'Air Conditioning Failure in Air-Conditioned Bus Line 138',
    category: 'vehicle_condition',
    channel: 'website',
    priority: 'low',
    status: 'completed',
    complainantName: 'Anonymous Passenger',
    complainantContact: '',
    complainantEmail: '',
    isAnonymous: true,
    busRoute: '138 (Phra Pradaeng - Mochit 2)',
    vehicleId: '12-9981 / Blue-NGV',
    incidentTime: '2026-10-05T16:00:00',
    incidentLocation: 'Expressway Route Phra Pradaeng',
    narrative: 'Air conditioning compressor failed during hot afternoon on highway route. Interior temperature exceeded 35C. Driver opened emergency roof hatch.',
    tags: ['#VehicleCondition', '#AirConditioning', '#FleetMaintenance'],
    assignedInvestigator: 'Chaiwat T.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 5',
    slaDeadline: '2026-10-09T18:00:00',
    createdAt: '2026-10-05T17:30:00',
    updatedAt: '2026-10-08T09:00:00',
    approvalStatus: 'approved',
    managerNotes: 'Vehicle sent to workshop for complete AC compressor and belt overhaul. QC verified.'
  },
  {
    id: 'CR-2026-00125',
    subject: 'พนักงานเก็บค่าโดยสารแสดงกิริยาไม่สุภาพและไม่ทอนเงิน สาย 140',
    category: 'ticketing_issue',
    channel: 'hotline',
    priority: 'high',
    status: 'overdue',
    complainantName: 'Prasert W.',
    complainantContact: '082-777-6655',
    complainantEmail: 'prasert.w@example.com',
    isAnonymous: false,
    busRoute: '140 (Samae Dam - Victory Monument)',
    vehicleId: '14-2201',
    incidentTime: '2026-10-03T18:20:00',
    incidentLocation: 'Pratunam Bus Stop',
    narrative: 'Fare collector spoke aggressively using offensive language when passenger gave 100 Baht bill and did not return the 75 Baht change despite reminders.',
    tags: ['#FareCollector', '#TicketingIssue', '#Overdue'],
    assignedInvestigator: 'Kittipong N.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 5',
    slaDeadline: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-10-03T19:00:00',
    updatedAt: '2026-10-04T11:00:00',
    approvalStatus: 'pending',
    managerNotes: 'Urgent disciplinary committee hearing required.'
  },
  {
    id: 'CR-2026-00126',
    subject: 'เบาะที่นั่งชำรุดมีตะปูโผล่ทำให้เสื้อผ้าผู้โดยสารขาด สาย 536',
    category: 'vehicle_condition',
    channel: 'social_media',
    priority: 'medium',
    status: 'pending_approval',
    complainantName: 'Nalinee R.',
    complainantContact: '086-999-3322',
    complainantEmail: 'nalinee.r@example.com',
    isAnonymous: false,
    busRoute: '536 (Paknam - Mochit 2)',
    vehicleId: '11-6644',
    incidentTime: '2026-10-13T11:15:00',
    incidentLocation: 'Bangna Junction',
    narrative: 'Seat row 4 on the right has an exposed metal bracket screw that tore passenger clothing. Passenger notified conductor who taped it temporarily.',
    tags: ['#SafetyHazard', '#SeatRepair', '#PendingApproval'],
    assignedInvestigator: 'Wichai S.',
    assignedManager: 'Somchai T.',
    zone: 'Zone 3',
    slaDeadline: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-10-13T12:30:00',
    updatedAt: '2026-10-14T15:00:00',
    approvalStatus: 'pending',
    managerNotes: 'Seat repaired and compensation process for damaged clothing drafted for manager sign-off.'
  }
];

export const INITIAL_EVIDENCE: Evidence[] = [
  {
    id: 'ev-001',
    caseId: 'CR-2026-00124',
    fileName: 'dashcam_front.mp4',
    fileType: 'video',
    fileSize: '48.2 MB',
    uploadedAt: '2026-10-13T10:15:00',
    uploadedBy: 'Kittipong N.',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  },
  {
    id: 'ev-002',
    caseId: 'CR-2026-00124',
    fileName: 'ticket_stub.jpg',
    fileType: 'image',
    fileSize: '2.4 MB',
    uploadedAt: '2026-10-12T09:30:00',
    uploadedBy: 'Sompong Jai-dee',
    fileUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'ev-003',
    caseId: 'CR-2026-00124',
    fileName: 'witness_stmt_1.pdf',
    fileType: 'document',
    fileSize: '420 KB',
    uploadedAt: '2026-10-13T14:00:00',
    uploadedBy: 'Kittipong N.',
    fileUrl: ''
  },
  {
    id: 'ev-004',
    caseId: 'CR-2026-00124',
    fileName: 'telemetry_speed_log.csv',
    fileType: 'document',
    fileSize: '1.1 MB',
    uploadedAt: '2026-10-14T09:20:00',
    uploadedBy: 'Kittipong N.',
    fileUrl: ''
  }
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 'tm-001',
    caseId: 'CR-2026-00124',
    title: 'Complaint Logged via Hotline 1348',
    description: 'Complainant Sompong Jai-dee registered incident regarding aggressive driving on Route 514.',
    type: 'created',
    timestamp: '2026-10-12T09:00:00',
    author: 'Hotline Agent #42'
  },
  {
    id: 'tm-002',
    caseId: 'CR-2026-00124',
    title: 'Case Assigned to Lead Investigator',
    description: 'Assigned to Kittipong N. (Zone 4) with 5-day SLA deadline.',
    type: 'status_change',
    timestamp: '2026-10-12T10:15:00',
    author: 'Somchai T. (Zone Manager)'
  },
  {
    id: 'tm-003',
    caseId: 'CR-2026-00124',
    title: 'GPS & Telemetry Data Retrieved',
    description: 'GPS logs confirm vehicle #12-3456 was at Ratchada intersection at 17:47. Speed telemetry indicates heavy braking events (3g force) preceding the intersection.',
    type: 'investigation',
    timestamp: '2026-10-13T15:30:00',
    author: 'Kittipong N.'
  },
  {
    id: 'tm-004',
    caseId: 'CR-2026-00124',
    title: 'Driver Interview Scheduled',
    description: 'Interview set for Oct 16, 09:00 with driver Mr. Wanchai P. at Zone 4 depot office.',
    type: 'investigation',
    timestamp: '2026-10-14T11:00:00',
    author: 'Kittipong N.'
  }
];
